name: vNext CI

on:
  merge_group:
  push:
    branches:
      - v-next
      - robust-compiler-downloader-debug
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        package: [hardhat]
        os: [macos-13]
        node: [22]
        attempt: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    name: "[${{ matrix.package }}] ci on ${{ matrix.os }} (Node ${{ matrix.node }}; attempt ${{ matrix.attempt }})"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: v-next/${{ matrix.package }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm build
      - name: Run tests
        env:
          __DO_NOT_USE_IS_HARDHAT_CI: true
        run: pnpm run test:only
